# Generated by Django 3.0 on 2019-12-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanPascua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('peso', models.DecimalField(decimal_places=1, max_digits=2)),
                ('valor', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos', verbose_name='Imagen')),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
